version : "3.9"

services:
  java-service:
    build:
      dockerfile: Dockerfile
      context: ./java-service
    image: java-service:latest
    container_name: java-container
    ports:
      - "8080:8080"
    networks:
      - mynet

  python-service:
    build:
      dockerfile: Dockerfile
      context: ./python-service
    depends_on:
      - java-service
    image: python-service:latest
    container_name: python-container
    #Setting PYTHONUNBUFFERED=TRUE or PYTHONUNBUFFERED=1 (they are equivalent)
    #allows for log messages to be immediately dumped to the stream instead of
    #being buffered. This is useful for receiving timely log messages and
    #avoiding situations where the application crashes without emitting a
    #relevant message due to the message being "stuck" in a buffer.
    environment:
       - PYTHONUNBUFFERED=1
       - JAVA_SERVICE_URL=http://java-container
       - JAVA_SERVICE_PORT=8080
    ports:
      - "5000:5000"
    networks:
      - mynet

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus
    networks:
      - mynet

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    hostname: grafana
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
